// examples/react/src/examples/reusable-array/App.tsx
import { useForm } from "@kintools/form-react";
import { useFormDevtools } from "@kintools/form-devtools-react";
import { email, required } from "@kintools/form-validators";
import { ArrayField } from "./components/ArrayField.tsx";
import { SubmitButton } from "./components/SubmitButton.tsx";
import { TextField } from "./components/TextField.tsx";

// Stable per-member identity for React's list `key` (see `ArrayField`'s
// `itemKey`), carried on the member object itself under this symbol.
// Symbol-keyed, so `JSON.stringify` ignores it — no submit-time filtering
// needed to keep it off the wire.
const TEAM_MEMBER_ID = Symbol();
let nextTeamMemberId = 0;

type TeamMember = { name: string; email: string; [TEAM_MEMBER_ID]: number };

type Profile = {
  displayName: string;
  skills: string[];
  teamMembers: TeamMember[];
};

export default function App() {
  const form = useForm<Profile>({
    initialValue: {
      displayName: "",
      skills: [],
      teamMembers: [],
    },
    onSubmit: async (form) => {
      // Simulate a network request.
      await new Promise((resolve) => setTimeout(resolve, 800));
      alert(
        `Saved ${form.value.skills.length} skill(s) and ${form.value.teamMembers.length} team member(s).`,
      );
    },
  });

  useFormDevtools(form);

  return (
    <div className="w-full max-w-md rounded-lg bg-white p-8 shadow-md">
      <h1 className="text-xl font-semibold text-gray-900">Team profile</h1>

      <form
        className="mt-6 space-y-6"
        onSubmit={form.handleSubmit}
        noValidate
      >
        <TextField
          api={form.field("displayName", {
            validators: required("Display name is required"),
          })}
          label="Display name"
          required
        />

        <ArrayField
          api={form.field("skills")}
          label="Skills"
          itemKey={(skill) => skill}
          newItem={() => ""}
        >
          {(api, index) => (
            <TextField
              api={api.field(`${index}`, {
                validators: required("Can't be empty"),
              })}
              placeholder="e.g. TypeScript"
            />
          )}
        </ArrayField>

        <ArrayField
          api={form.field("teamMembers")}
          label="Team members"
          itemKey={(member) => member[TEAM_MEMBER_ID]}
          newItem={() => ({
            name: "",
            email: "",
            [TEAM_MEMBER_ID]: ++nextTeamMemberId,
          })}
        >
          {(group, index) => (
            <div className="grid grid-cols-2 gap-2">
              <TextField
                api={group.field(`${index}.name`, {
                  validators: [required("Required")],
                })}
                placeholder="Name"
              />
              <TextField
                api={group.field(`${index}.email`, {
                  validators: [required("Required"), email("Invalid email")],
                })}
                placeholder="Email"
              />
            </div>
          )}
        </ArrayField>

        <SubmitButton api={form} className="w-full" pendingLabel="Saving…">
          Save profile
        </SubmitButton>
      </form>
    </div>
  );
}

// examples/lit/src/examples/reusable-array/App.ts
import { html } from "lit";
import { type FieldApi, FormApi } from "@kintools/form-lit";
import { email, required } from "@kintools/form-validators";
import "./components/ArrayField.ts";
import "./components/SubmitButton.ts";
import "./components/TextField.ts";

// Stable per-member identity for `repeat()`'s key (see `ArrayField`'s
// `.itemKey`), carried on the member object itself under this symbol.
// Symbol-keyed, so `JSON.stringify` ignores it - no submit-time filtering
// needed to keep it off the wire.
const TEAM_MEMBER_ID = Symbol();
let nextTeamMemberId = 0;

type TeamMember = { name: string; email: string; [TEAM_MEMBER_ID]: number };

type Profile = {
  displayName: string;
  skills: string[];
  teamMembers: TeamMember[];
};

export default function App(): unknown {
  const form = new FormApi<Profile>({
    initialValue: {
      displayName: "",
      skills: [],
      teamMembers: [],
    },
    onSubmit: async (form) => {
      // Simulate a network request.
      await new Promise((resolve) => setTimeout(resolve, 800));
      alert(
        `Saved ${form.value.skills.length} skill(s) and ${form.value.teamMembers.length} team member(s).`,
      );
    },
  });

  return html`
    <div class="w-full max-w-md rounded-lg bg-white p-8 shadow-md">
      <h1 class="text-xl font-semibold text-gray-900">Team profile</h1>

      <form class="mt-6 space-y-6" @submit=${form.handleSubmit} novalidate>
        <reusable-array-text-field
          .api=${form.field("displayName", {
            validators: required("Display name is required"),
          })}
          label="Display name"
          required
        ></reusable-array-text-field>

        <reusable-array-array-field
          .api=${form.field("skills")}
          label="Skills"
          .itemKey=${(skill: string) => skill}
          .newItem=${() => ""}
          .renderItem=${(api: FieldApi<string[], Profile>, index: number) =>
            html`
              <reusable-array-text-field
                .api=${api.field(`${index}`, {
                  validators: required("Can't be empty"),
                })}
                placeholder="e.g. TypeScript"
              ></reusable-array-text-field>
            `}
        ></reusable-array-array-field>

        <reusable-array-array-field
          .api=${form.field("teamMembers")}
          label="Team members"
          .itemKey=${(member: TeamMember) => member[TEAM_MEMBER_ID]}
          .newItem=${() => ({
            name: "",
            email: "",
            [TEAM_MEMBER_ID]: ++nextTeamMemberId,
          })}
          .renderItem=${(
            group: FieldApi<TeamMember[], Profile>,
            index: number,
          ) =>
            html`
              <div class="grid grid-cols-2 gap-2">
                <reusable-array-text-field
                  .api=${group.field(`${index}.name`, {
                    validators: [required("Required")],
                  })}
                  placeholder="Name"
                ></reusable-array-text-field>
                <reusable-array-text-field
                  .api=${group.field(`${index}.email`, {
                    validators: [required("Required"), email("Invalid email")],
                  })}
                  placeholder="Email"
                ></reusable-array-text-field>
              </div>
            `}
        ></reusable-array-array-field>

        <reusable-array-submit-button
          .api=${form}
          button-class="w-full"
          pending-label="Saving…"
          label="Save profile"
        ></reusable-array-submit-button>
      </form>
    </div>
  `;
}
