// examples/lit/src/examples/server-validation/components/TextField.ts
import { html, LitElement, nothing } from "lit";
import { property } from "lit/decorators.js";
import { __decorate } from "tslib";
import { type FieldApi, WatchController } from "@kintools/form-lit";

const inputClasses = (invalid: boolean) =>
  `mt-1 block w-full rounded-md border px-3 py-2 text-sm text-gray-900 shadow-sm focus:outline-none focus:ring-2 ${
    invalid
      ? "border-red-400 focus:border-red-400 focus:ring-red-200"
      : "border-gray-300 focus:border-blue-500 focus:ring-blue-200"
  }`;

export class TextField extends LitElement {
  // See `SubmitButton.ts`'s own doc comment for why these are `declare`d
  // rather than real class fields, with defaults set in the constructor
  // instead of a field initializer.
  // deno-lint-ignore no-explicit-any
  declare api: FieldApi<string, any>;
  declare label?: string;
  declare required?: boolean;
  declare type: string;
  declare autocomplete?: string;
  declare placeholder?: string;
  declare inputClass: string;

  readonly #watch = new WatchController(this, () => this.api);
  // A per-instance counter, not `field.id`: `field.id` is only guaranteed
  // stable across reorders (what makes it suitable as a list key), not
  // unique/matched between environments the way a DOM id needs to be.
  static #nextId = 0;
  readonly #id = `text-field-${TextField.#nextId++}`;

  constructor() {
    super();
    this.type = "text";
    this.inputClass = "";
  }

  override createRenderRoot(): this {
    return this;
  }

  override render(): unknown {
    const field = this.#watch.value;
    const showError = field.invalid && field.touched;
    const inputId = `${field.name}-${this.#id}`;

    return html`
      <div>
        ${this.label
          ? html`
            <label for=${inputId} class="block text-sm font-medium text-gray-700">
              ${this.label}
              ${this.required
                ? html`<span class="ml-0.5 text-red-500">*</span>`
                : nothing}
            </label>
          `
          : nothing}
        <input
          id=${inputId}
          type=${this.type}
          autocomplete=${this.autocomplete ?? nothing}
          placeholder=${this.placeholder ?? nothing}
          .value=${field.value}
          @blur=${field.handleBlur}
          @input=${(event: Event) =>
            field.handleChange((event.target as HTMLInputElement).value)}
          class="${inputClasses(!!showError)} ${this.inputClass}"
        >
        ${showError
          ? html`<p class="mt-1 text-sm text-red-600">${field.error}</p>`
          : nothing}
      </div>
    `;
  }
}

__decorate(
  [property({ attribute: false })],
  TextField.prototype,
  "api",
  void 0,
);
__decorate(
  [property({ type: String })],
  TextField.prototype,
  "label",
  void 0,
);
__decorate(
  [property({ type: Boolean })],
  TextField.prototype,
  "required",
  void 0,
);
__decorate(
  [property({ type: String })],
  TextField.prototype,
  "type",
  void 0,
);
__decorate(
  [property({ type: String })],
  TextField.prototype,
  "autocomplete",
  void 0,
);
__decorate(
  [property({ type: String })],
  TextField.prototype,
  "placeholder",
  void 0,
);
__decorate(
  [property({ type: String, attribute: "input-class" })],
  TextField.prototype,
  "inputClass",
  void 0,
);

customElements.define("server-validation-text-field", TextField);

declare global {
  interface HTMLElementTagNameMap {
    "server-validation-text-field": TextField;
  }
}

// examples/react/src/examples/server-validation/components/TextField.tsx
import { type InputHTMLAttributes, type ReactNode, useId } from "react";
import { type FieldApi, useWatch } from "@kintools/form-react";

const inputClasses = (invalid: boolean) =>
  `mt-1 block w-full rounded-md border px-3 py-2 text-sm text-gray-900 shadow-sm focus:outline-none focus:ring-2 ${
    invalid
      ? "border-red-400 focus:border-red-400 focus:ring-red-200"
      : "border-gray-300 focus:border-blue-500 focus:ring-blue-200"
  }`;

export type TextFieldProps<TParentValue> =
  & {
    api: FieldApi<string, TParentValue>;
    label?: ReactNode;
    required?: boolean | ReactNode;
  }
  & Omit<
    InputHTMLAttributes<HTMLInputElement>,
    "id" | "value" | "onChange" | "onBlur"
  >;

export function TextField<const TParentValue>(
  props: TextFieldProps<TParentValue>,
): ReactNode {
  const { api, label, required, className, ...inputProps } = props;
  const { error, name, invalid, touched, value, handleBlur, handleChange } =
    useWatch(api);
  const showError = invalid && touched;
  // `useId`, not `field.id`: `field.id` is a plain module-level counter
  // (stable across reorders, which is what makes it suitable as a React
  // `key`, see its own doc comment), not a server/client-matched value, so
  // rendering it into the DOM would mismatch under SSR.
  const reactId = useId();
  const inputId = `${name}-${reactId}`;

  return (
    <div>
      {label && (
        <label
          htmlFor={inputId}
          className="block text-sm font-medium text-gray-700"
        >
          {label}
          {required && (
            <span className="ml-0.5 text-red-500">
              {required === true ? "*" : required}
            </span>
          )}
        </label>
      )}
      <input
        {...inputProps}
        id={inputId}
        value={value}
        onBlur={handleBlur}
        onChange={(event) => handleChange(event.target.value)}
        className={`${inputClasses(!!showError)} ${className ?? ""}`}
      />
      {showError && <p className="mt-1 text-sm text-red-600">{error}</p>}
    </div>
  );
}
