// examples/react/src/examples/flat-array-validation/components/TextField.tsx
import { type InputHTMLAttributes, type ReactNode, useId } from "react";
import { type FieldApi, useWatch } from "@kintools/form-react";

const inputClasses = (invalid: boolean) =>
  `mt-1 block w-full rounded-md border px-3 py-2 text-sm text-gray-900 shadow-sm focus:outline-none focus:ring-2 ${
    invalid
      ? "border-red-400 focus:border-red-400 focus:ring-red-200"
      : "border-gray-300 focus:border-blue-500 focus:ring-blue-200"
  }`;

export type TextFieldProps<TParentValue> =
  & Omit<
    InputHTMLAttributes<HTMLInputElement>,
    "id" | "value" | "onChange" | "onBlur"
  >
  & {
    api: FieldApi<string, TParentValue>;
    label?: ReactNode;
  };

// This example has no per-field validators at all. Every message comes from
// the one whole-form `toSchemaValidator()` validator in `App.tsx`, surfaced
// through `field.error` (which falls back to the schema slice when the field
// has no own error), so this `TextField` takes no `validators` prop like the
// other examples' do.
export function TextField<const TParentValue>({
  api,
  label,
  className,
  ...inputProps
}: TextFieldProps<TParentValue>): ReactNode {
  const field = useWatch(api);
  const showError = field.invalid && field.touched;
  const error = field.error;
  const value = field.value;
  // `useId`, not `field.id`: `field.id` is a plain module-level counter
  // (stable across reorders, which is what makes it suitable as a React
  // `key`, see its own doc comment), not a server/client-matched value, so
  // rendering it into the DOM would mismatch under SSR.
  const reactId = useId();
  const inputId = `${field.name}-${reactId}`;

  return (
    <div>
      {label && (
        <label
          htmlFor={inputId}
          className="block text-sm font-medium text-gray-700"
        >
          {label}
        </label>
      )}
      <input
        {...inputProps}
        id={inputId}
        value={value}
        onBlur={field.handleBlur}
        onChange={(event) => field.handleChange(event.target.value)}
        className={`${inputClasses(!!showError)} ${className ?? ""}`}
      />
      {showError && <p className="mt-1 text-sm text-red-600">{error}</p>}
    </div>
  );
}

// examples/lit/src/examples/flat-array-validation/components/TextField.ts
import { html, LitElement, nothing } from "lit";
import { property } from "lit/decorators.js";
import { __decorate } from "tslib";
import { type FieldApi, WatchController } from "@kintools/form-lit";

const inputClasses = (invalid: boolean) =>
  `mt-1 block w-full rounded-md border px-3 py-2 text-sm text-gray-900 shadow-sm focus:outline-none focus:ring-2 ${
    invalid
      ? "border-red-400 focus:border-red-400 focus:ring-red-200"
      : "border-gray-300 focus:border-blue-500 focus:ring-blue-200"
  }`;

// This example has no per-field validators at all. Every message comes from
// the one whole-form `toSchemaValidator()` validator in `App.ts`, surfaced
// through `field.error` (which falls back to the schema slice when the field
// has no own error), so this text field takes no `required` property like the
// other examples' do.
export class TextField extends LitElement {
  // See `SubmitButton.ts`'s own doc comment for why these are `declare`d
  // rather than real class fields, with defaults set in the constructor
  // instead of a field initializer.
  // deno-lint-ignore no-explicit-any
  declare api: FieldApi<string, any>;
  declare label?: string;
  declare placeholder?: string;
  declare inputClass: string;

  readonly #watch = new WatchController(this, () => this.api);
  // A per-instance counter, not `field.id`: `field.id` is only guaranteed
  // stable across reorders (what makes it suitable as a list key), not
  // unique/matched between environments the way a DOM id needs to be.
  static #nextId = 0;
  readonly #id = `text-field-${TextField.#nextId++}`;

  constructor() {
    super();
    this.inputClass = "";
  }

  override createRenderRoot(): this {
    return this;
  }

  override render(): unknown {
    const field = this.#watch.value;
    const showError = field.invalid && field.touched;
    const error = field.error;
    const inputId = `${field.name}-${this.#id}`;

    return html`
      <div>
        ${this.label
          ? html`
            <label for=${inputId} class="block text-sm font-medium text-gray-700">
              ${this.label}
            </label>
          `
          : nothing}
        <input
          id=${inputId}
          placeholder=${this.placeholder ?? nothing}
          .value=${field.value}
          @blur=${field.handleBlur}
          @input=${(event: Event) =>
            field.handleChange((event.target as HTMLInputElement).value)}
          class="${inputClasses(!!showError)} ${this.inputClass}"
        >
        ${showError
          ? html`<p class="mt-1 text-sm text-red-600">${error}</p>`
          : nothing}
      </div>
    `;
  }
}

__decorate(
  [property({ attribute: false })],
  TextField.prototype,
  "api",
  void 0,
);
__decorate(
  [property({ type: String })],
  TextField.prototype,
  "label",
  void 0,
);
__decorate(
  [property({ type: String })],
  TextField.prototype,
  "placeholder",
  void 0,
);
__decorate(
  [property({ type: String, attribute: "input-class" })],
  TextField.prototype,
  "inputClass",
  void 0,
);

customElements.define("flat-array-validation-text-field", TextField);

declare global {
  interface HTMLElementTagNameMap {
    "flat-array-validation-text-field": TextField;
  }
}
